package com.exolade.bizincode.retail.misc;

public enum MagazineCategory {
	ANIMAL, ART, AUTOMOBILE, BUSINESS, ENTERTAINMENT, CHILDREN, TECHNOLOGY, CRAFT, DESIGN, EDUCATION,
	FASHION, FOOD, WINE, GAME, HOBBY, HEALTH, HISTORY, GARDENING, SPORTS, SCIENCE, NATURE, 
	TRAVEL, INTERNATIONAL
}
